# Generated by Django 5.2.3 on 2025-06-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=255, verbose_name='Função')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salário')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave pix')),
                ('banco', models.CharField(max_length=255, verbose_name='Banco')),
                ('contato', models.CharField(max_length=20, verbose_name='Contato')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('frequencia_pagamento', models.CharField(choices=[('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal')], max_length=20, verbose_name='Frequência de pagamento')),
                ('status', models.CharField(choices=[('AtivoAT', 'Ativo'), ('Inativo', 'Inativo'), ('Férias', 'Férias')], max_length=10, verbose_name='Status')),
            ],
        ),
    ]
