# Generated by Django 5.2.3 on 2025-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=255, verbose_name='Função')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salário')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave pix')),
                ('banco', models.CharField(max_length=255, verbose_name='Banco')),
            ],
        ),
    ]
